---
  - name: diagnose_vsam
    zos_mvs_raw:
      program_name: idcams
      # parm:
      auth: true
      dds:
        - dd_data_set:
            dd_name: diagdd
            data_set_name: "{{cat_name}}"
            disposition: shr
        - dd_input:
            dd_name: sysin
            content:
              - " DIAGNOSE ICFCATALOG INFILE(DIAGDD)"
        - dd_output:
            dd_name: sysprint
            return_content:
              type: text
          
        

      