---
  - name: export
    zos_mvs_raw:
      program_name: idcams
      auth: true
      dds:
          - dd_data_set:
              dd_name: EXPDD
              data_set_name: "{{export_file}}"
              disposition: new
              reuse: true
              type: seq

            
          - dd_output:
              dd_name: SYSPRINT
              return_content:
                type: text
            
          - dd_input:
              dd_name: SYSIN
              content:
                  -  " EXPORT {{cat_name}}  OUTFILE(EXPDD) TEMPORARY"
                    
          
          