---
    - hosts: zos
      gather_facts: no
      
      environment:
        "{{default_environment}}"
      collections:
        - ibm.ibm_zos_core
      
      tasks:
        - name: alloc_dsn
          zos_data_set:
            name: MARLM.SAMPLEX
            type: seq
            state: present
            
        