---
  - hosts: zos
    gather_facts: no
    # environment:
    #   "{{default_environment}}"
    collections:
      - ibm.ibm_zos_core
    
    tasks:
      - name: Execute shell commands
        shell: zowe files ls ds "bill"
        delegate_to: localhost
      