---
  - hosts: zos
    gather_facts: no
    environment:
      "{{default_environment}}"
    collections:
      - ibm.ibm_zos_core
    vars:
      cat_name: CATALOG.T51061.TEST1
    
    tasks:
      - name: backup  
        include_tasks: ../tasks/listcat.yml
        
      