---
  - hosts: zos
    gather_facts: no
    environment:
      "{{default_environment}}"
    vars:
        cat_name: CATALOG.T51061.TEST
    collections:
      - ibm.ibm_zos_core
    
    tasks:
        - name: unlock_cat
          zos_mvs_raw:
            program_name: idcams
            auth: true
            dds:
              - dd_output:
                  dd_name: SYSPRINT
                  return_content:
                    type: text
              - dd_input:
                  dd_name: SYSIN
                  content:
                    - " ALTER CATALOG.T51061.TEST UNLOCK"                

            
                
          
          
      